name: houzy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Auth
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI & Utilities
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.5
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  http: ^0.13.6
  imagekit: ^0.0.5
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  shimmer: ^2.0.0
  animate_do: ^3.0.2
  permission_handler: ^11.0.1
  image_picker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/book-open-text.png
    - assets/images/circle-help.png
    - assets/images/cleaning.png
    - assets/images/googleicon.png
    - assets/images/house.png
    - assets/images/houzylogoimage.png
    - assets/images/loginsvg.png
    - assets/images/notebook.png
    - assets/images/servicesimage.png
    - assets/images/splashimage1.png
    - assets/images/splashimage2.png
    - assets/images/store.png
    - assets/images/user.png
    - assets/images/serviceimage1.png
    - assets/images/customerimage.png

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
